spring.application.name=dealership-api
spring.datasource.url=jdbc:mysql://localhost:3306/springdealership
spring.datasource.username=root
spring.datasource.password=yearup2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true